defmodule RespawnedWeb.Communities.Management.InfoLive do
  use RespawnedWeb, :live_view

  @impl true
  def render(assigns) do
    ~H"""
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    <div>INFO</div>
    """
  end
end
